name: Parser CI

on:
  push:
    branches: [ "main" ]

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 1. СНАЧАЛА устанавливаем саму библиотеку Playwright через pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      # 2. ТОЛЬКО ПОТОМ скачиваем браузеры (теперь модуль уже найден)
      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps chromium

      # 3. Запускаем твой скрипт
      - name: Run Script
        run: python main.py
