name: Parser CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Установлены все необходимые зависимости для нового скрипта
          pip install requests tqdm

      - name: Run Parser
        run: python main.py

      - name: Upload Results
        if: always() # Загружать артефакты даже если парсер упал (для проверки прогресса)
        uses: actions/upload-artifact@v4
        with:
          name: aniliberty-data
          # Все файлы теперь корректно лежат внутри mirrors/
          path: |
            mirrors/aniliberty_all.m3u
            mirrors/parser_progress.json
            mirrors/posters/
          retention-days: 5
          if-no-files-found: warn # Не валить job, если файлов еще нет
